"use client";

import { useState, useEffect } from "react";
import { Bot, Target, CheckCircle, AlertTriangle, Lightbulb, Briefcase, GraduationCap, Code2, Award, Star, Crown, Sparkles, LayoutDashboard } from "lucide-react";
import Link from "next/link";

interface AnalysisResult {
  name: string;
  skills: string[];
  years_experience: number;
  education: string;
  strengths: string[];
  weaknesses: string[];
  recommendations: string[];
  ats_score: number;
}

export default function SharedReportPage({ params }: { params: { id: string } }) {
  const [analysis, setAnalysis] = useState<AnalysisResult | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchSharedAnalysis = async () => {
      try {
        const response = await fetch(`/api/share/${params.id}`);
        const data = await response.json();

        if (!response.ok) {
          throw new Error(data.error || "Failed to load shared analysis");
        }

        setAnalysis(data.analysis);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to load");
      } finally {
        setIsLoading(false);
      }
    };

    fetchSharedAnalysis();
  }, [params.id]);

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-green-600"></div>
          <p className="mt-4 text-gray-600">Loading shared report...</p>
        </div>
      </div>
    );
  }

  if (error || !analysis) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <AlertTriangle className="w-16 h-16 text-red-500 mx-auto mb-4" />
          <h1 className="text-2xl font-bold text-gray-800 mb-2">Report Not Found</h1>
          <p className="text-gray-600">This shared report may have expired or been removed.</p>
          <Link href="/" className="mt-4 inline-block bg-green-600 text-white px-6 py-2 rounded-lg hover:bg-green-700">
            Go Home
          </Link>
        </div>
      </div>
    );
  }

  const getScoreColor = (score: number) => {
    if (score >= 80) return "text-green-600";
    if (score >= 60) return "text-emerald-600";
    return "text-orange-600";
  };

  return (
    <div className="min-h-screen p-4 md:p-8 bg-gradient-to-br from-green-50 to-emerald-100">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="flex justify-center mb-4">
            <div className="bg-gradient-to-br from-green-500 to-emerald-600 p-4 rounded-2xl shadow-2xl">
              <Bot className="w-16 h-16 text-white" />
            </div>
          </div>
          <h1 className="text-3xl md:text-4xl font-bold bg-gradient-to-r from-green-600 to-emerald-600 bg-clip-text text-transparent">
            Shared Resume Analysis
          </h1>
          <p className="text-gray-600 mt-2">Report for {analysis.name}</p>
        </div>

        {/* Analysis Report */}
        <div className="bg-white rounded-2xl shadow-xl overflow-hidden">
          <div className="bg-gradient-to-r from-green-600 to-emerald-600 text-white p-6">
            <h2 className="text-2xl font-bold">Analysis Report</h2>
            <p className="opacity-90 mt-1">Generated by AI Resume Analyzer</p>
          </div>

          <div className="p-6 space-y-6">
            {/* Candidate */}
            <div className="border-b pb-4">
              <div className="flex items-center gap-2 text-green-600 mb-2">
                <Crown className="w-4 h-4" />
                <span className="text-sm font-semibold uppercase">Candidate</span>
              </div>
              <p className="text-3xl font-bold text-gray-800">{analysis.name}</p>
            </div>

            {/* ATS Score */}
            <div className="bg-green-50 rounded-xl p-5">
              <div className="flex items-center gap-2 mb-3">
                <Target className="w-5 h-5 text-green-600" />
                <h3 className="text-lg font-semibold">ATS Compatibility Score</h3>
              </div>
              <div className="flex items-center gap-4">
                <div className="text-4xl font-bold text-green-600">{analysis.ats_score}%</div>
                <div className="flex-1 h-3 bg-gray-200 rounded-full overflow-hidden">
                  <div className="h-full bg-green-500 rounded-full" style={{ width: `${analysis.ats_score}%` }} />
                </div>
              </div>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-green-50 rounded-lg p-4 text-center">
                <Briefcase className="w-6 h-6 mx-auto text-green-600 mb-2" />
                <p className="text-2xl font-bold text-green-600">{analysis.years_experience}</p>
                <p className="text-sm text-gray-600">Years Experience</p>
              </div>
              <div className="bg-emerald-50 rounded-lg p-4 text-center">
                <GraduationCap className="w-6 h-6 mx-auto text-emerald-600 mb-2" />
                <p className="text-lg font-bold text-emerald-600">{analysis.education}</p>
                <p className="text-sm text-gray-600">Education</p>
              </div>
            </div>

            {/* Skills */}
            <div>
              <h3 className="text-lg font-bold mb-3 flex items-center gap-2">
                <Code2 className="w-5 h-5 text-green-600" />
                Technical Skills
              </h3>
              <div className="flex flex-wrap gap-2">
                {analysis.skills.map((skill, i) => (
                  <span key={i} className="bg-green-100 text-green-800 px-3 py-1.5 rounded-full text-sm">
                    {skill}
                  </span>
                ))}
              </div>
            </div>

            {/* Strengths */}
            <div className="bg-green-50 rounded-lg p-4">
              <h3 className="text-lg font-bold text-green-800 mb-3 flex items-center gap-2">
                <Award className="w-5 h-5" />
                Strengths
              </h3>
              <ul className="space-y-2">
                {analysis.strengths.map((strength, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <Star className="w-4 h-4 text-green-500 mt-0.5" />
                    <span>{strength}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Weaknesses */}
            <div className="bg-orange-50 rounded-lg p-4">
              <h3 className="text-lg font-bold text-orange-800 mb-3 flex items-center gap-2">
                <AlertTriangle className="w-5 h-5" />
                Areas for Improvement
              </h3>
              <ul className="space-y-2">
                {analysis.weaknesses.map((weakness, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <div className="w-1.5 h-1.5 bg-orange-500 rounded-full mt-2"></div>
                    <span>{weakness}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Recommendations */}
            <div className="bg-purple-50 rounded-lg p-4">
              <h3 className="text-lg font-bold text-purple-800 mb-3 flex items-center gap-2">
                <Lightbulb className="w-5 h-5" />
                Recommendations
              </h3>
              <ul className="space-y-2">
                {analysis.recommendations.map((rec, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-purple-600 font-bold">{i + 1}.</span>
                    <span>{rec}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Footer */}
            <div className="text-center text-xs text-gray-400 pt-4 border-t">
              <LayoutDashboard className="w-3 h-3 inline mr-1" />
              Generated by AI Resume Analyzer • Shared Report
            </div>
          </div>
        </div>

        {/* Back to Home */}
        <div className="text-center mt-6">
          <Link href="/" className="text-green-600 hover:underline">
            ← Back to AI Resume Analyzer
          </Link>
        </div>
      </div>
    </div>
  );
}